### ISSUE TITLE
Support Credential Schema

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-kt#100]
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "credentialSchema": {
    "id": "https://example.org/examples/degree.json",
    "type": "JsonSchemaValidator2018"
  }
}

**Comment by decentralgabe** [comment]
duplicate of https://github.com/TBD54566975/web5-kt/issues/114 ?

**Comment by nitro-neal** [comment]
closing for 114
