### ISSUE TITLE
Add alg support for EdDSA

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/web5-kt#101]
**Describe the bug**
While implementing an application using these new Kotlin sdks, I was trying to integrate with an issuer, and ran into a cryptographic algorithm incompatibility. The issuer supports `EdDSA` but the call here does not:

```kotlin
val did = DidKey.create(InMemoryKeyManager(), CreateDidKeyOptions(algorithm = Algorithm("EdDSA")))
```

**To Reproduce:**
*Steps to reproduce the behavior:*

Try to create a did:key using EdDSA and you'll see the exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Algorithm EdDSA not supported
	at web5.sdk.crypto.Crypto.getKeyGenerator(Crypto.kt:187)
	at web5.sdk.crypto.Crypto.generatePrivateKey(Crypto.kt:77)
	at web5.sdk.crypto.InMemoryKeyManager.generatePrivateKey(InMemoryKeyManager.kt:42)
	at web5.sdk.crypto.KeyManager$DefaultImpls.generatePrivateKey$default(KeyManager.kt:31)
	at web5.sdk.dids.DidKey$Companion.create(DidKey.kt:89)
```

**Expected behavior:**
*A clear and concise description of what you expected to happen.*

I would expect the algorithm to be supported

**Comment by KendallWeihe** [comment]
Welp, this is a non-issue. Closing. 

I needed to include a supporting Curve, such as this...

```kotlin
val did = DidKey.create(InMemoryKeyManager(), CreateDidKeyOptions(algorithm = Algorithm("EdDSA"), curve = Curve.Ed25519))
```

**Comment by mistermoe** [comment]
you're running into this issue because `EdDSA` isn't specific enough. algorithms can have many curves and in this case `EdDSA` doesn't indicate 1 specific curve. doing the following should work:

```kt
val manager = InMemoryKeyManager()
val opts = CreateDidKeyOptions(algorithm = JWSAlgorithm.EdDSA, curve = Curve.Ed25519)
val did = DidKey.create(manager)
```
