### ISSUE TITLE
Automated GH Release Tag

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-kt#126]
We need a GH Action workflow to generate the GH releases.

Similar to https://github.com/TBD54566975/tbdex-js/pull/61

**Comment by andresuribe87** [comment]
@leordev would you mind clarifying the motivation behind this, and the desired behavior?

**Comment by leordev** [comment]
> @leordev would you mind clarifying the motivation behind this, and the desired behavior?

From the [Release Criteria](https://github.com/TBD54566975/sdk-development#release-criteria) defined in our our `sdk-development`:
> - Each Release will have an accompanying Github Release
> - Each Github Release will have an accompanying git tag that matches the version being published

That's pretty much it, we just need to make sure our release process is automated in such a way that it publish to Maven repo and has the same GH Release tag. This way it's easy to reference to the same source code. Which I think you did in #156
