### ISSUE TITLE
Explore and Add Feature usage examples in API Reference docs

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-kt#127]
We need to explore a way to publish feature usage examples.

In kotlin we have a way to do this, example: https://tbd54566975.github.io/tbdex-kt/protocol/tbdex.sdk.protocol.serialization/-json/index.html

I suspect that we could do that in tsdocs and rust too... Just as a long comment in markdown...

**Comment by andresuribe87** [comment]
@leordev does this belong in this repo? We already do it in markdown. See an example in  https://tbd54566975.github.io/web5-kt/docs/htmlMultiModule/credentials/index.html

**Comment by leordev** [comment]
@andresuribe87 I think this is exactly what we needed. @mistermoe can you confirm and close? (Or add more details if not?)
