### ISSUE TITLE
Create Verifiable Presentation and Verifiable Presentation Signing

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-kt#175]
We need Verifiable Presentations to wrap our presentationSubmission. An example can be found here: https://identity.foundation/presentation-exchange/#presentation-submissions

Currently we have this (only presentationSubmission object, no VerifiablePresentation)
```
val presentationSubmission: PresentationSubmission = PresentationExchange.createPresentationFromCredentials(listOf(vcJwt2, vcJwt1), pd)
```

I suggest we change it to be like this:
```
val vp: VerifiablePresentation = PresentationExchange.createPresentationFromCredentials(listOf(vcJwt2, vcJwt1), pd)
val vpJwt = vp.sign(issuerDid)
```

The change to our existing codebase will be to: 
* Create a VerifiablePresentation model object and 
* update the createPresentationFromCredentials to construct a vp that has a presentationSubmission from the inputs it is given

**Comment by andresuribe87** [comment]
This makes sense to me!

**Comment by nitro-neal** [comment]
https://github.com/TBD54566975/web5-kt/pull/184
