### ISSUE TITLE
refactor gradle module structure to match groupId

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/web5-kt#205]

**Comment by ALRubinger** [comment]
And package names should also match `groupId`. ie. If `groupId` is `xyz.block`, package names should start `xyz.block.web5.*`.

Note that in Kotlin the directory structure for the package names may be trimmed of common parents. So package names of `xyz.block.web5.common` can be in folder `src/main/kotlin/common`:

https://kotlinlang.org/docs/coding-conventions.html#directory-structure

**Comment by jiyoontbd** [comment]
closing - this is a dupe of an existing issue https://github.com/TBD54566975/web5-kt/issues/186
