### ISSUE TITLE
API Leak on com.nimbusds:nimbus-jose-jwt

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/web5-kt#229]
Submodule `crypto` in `web5-kt` is exporting an `api` dependency:

*  `api(libs.comNimbusdsJoseJwt)` > `com.nimbusds:nimbus-jose-jwt`

This means consumers are expected to use this dep directly. Encapsulate necessary operations in the `web5-kt` API such that we're not exposing the `com.nimbusds` APIs and asking users to rely on those. Our use internally should be an impl detail. Then move this to an `implementation` dependency.

**Comment by frankhinek** [comment]
Should be resolved by #110

**Comment by jiyoontbd** [comment]
Hopefully actually resolved by #236
