### ISSUE TITLE
API Leak: decentralized-identity:did-common-java

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/web5-kt#231]
Submodule `dids` in `web5-kt` is exporting an `api` dependency:

*  `api(libs.decentralizedIdentityDidCommonJava)` > `decentralized-identity:did-common-java`

This means consumers are expected to use this dep directly. Encapsulate necessary operations in the `web5-kt` API such that we're not exposing the `decentralized-identity` APIs and asking users to rely on those. Our use internally should be an impl detail. Then move this to an `implementation` dependency.

**Comment by frankhinek** [comment]
Will resolved by #185
