### ISSUE TITLE
Research and select OSS libs that will accelerate SDK development

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-kt#26]
Findings and recommendations to be prepared, to include:
- gaps between what is available as OSS vs. the required functionality
- library adoption/usage, state of maintenance, etc. (the typical things you'd consider when evaluating use of an OSS library in a project)

**Comment by andresuribe87** [comment]
Note that this is specific to an SDK that's specific to JVM environments (i.e. kotlin, Scala, and Java). 

Some none-functional requirements that we should consider:
* Private Keys should never leave a physical device boundary.
* Mobile needs to be full native, with a small footprint.
* Server has much more flexibility.

# Option 1

Build all native. Here's what we can reuse.

### DID SDK
* https://github.com/decentralized-identity/did-common-java - but does not provide facilities to create DIDs.
* Resolution can be done by doing network calls. If we need to do resolutions locally, without going to the network (this is limited to only some DID methods), we'll need to code it ourselves.
* Interactions with ION nodes need to be all coded from scratch.
* DID Key creation can use `com.github.richardbergquist:java-multicodec:main-SNAPSHOT` and `com.github.multiformats:java-multibase:v1.1.1`, both of which are incredibly new. The first is a personal github repo, but it only has multicodec definitions. The second came from ipfs folks. 
* DID expansion / resolution can use universal resolver, or we roll out our own. No libraries available.

### Credentials SDK
* `com.danubetech:verifiable-credentials-java:1.4.0` from danubetech. They're heavily involved with DIF. Actively maintained. Pulls lots of deps.
* No libraries found for status list. 
* Need to implement the lookup and verification of status list.
* No libraries found for presentation exchange. 
* https://github.com/microsoft/entra-verifiedid-wallet-library-android has a library but it looks hard to use and not very well documented.

### Crypto SDK
* Many options, all well maintained: 
  * https://www.bouncycastle.org/java.html
  * https://github.com/google/tink
  * https://connect2id.com/products/nimbus-jose-jwt
* nimbus is the one that seems easier to use with JSON technologies. Can so signing, verification, and JWT/JWS/JWK functions.
* Key management/storage
  * Android is well documented - starting point at https://developer.android.com/training/articles/security-tips#Crypto


# Option 2

Separate the mobile/server sdks as different workstreams.
For mobile, all of the above are still true.
For server, rework `ssi-service` so it fulfills the non-functional requirements needed fb

# Analysis

If we have accepted that we need a mobile SDK with all the mentioned functionality, then Option 1 needs to be done regardless. For option 1, the implementation may also be with C++ / Rust, and using JNI bindings. Rough estimate is that 1.5 months of work to get all the functionality, barring any design discussions on how things should be built.

Option 2 gets us server functionality significantly faster (all functionality within a week or less).

# Recomendation

Start with Option 2, and then do Option 1.

**Comment by mistermoe** [comment]
Closing this out. Feel free to reopen if needed @andresuribe87
