### ISSUE TITLE
`VerifiableCredential.create` make value for `type` optional 

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/web5-kt#320]
## Purpose
From [this](https://sq-tbd.slack.com/archives/C06TPS0TPUK/p1718689520386399) slack convo we've discovered that if we pass a value to `type` it will break LD processors who consume it. Since KCC is a JSON-LD construct. Right now we're able to do this in JS but not in KT. 

Currently: 
```
        val knownCustomerCredential = VerifiableCredential.create(
            type = "KnownCustomerCredential",
            issuer = issuerBearerDid.uri.toString(),
            subject = customerBearerDid.uri.toString(),
            expirationDate = expirationDate,
            data = KccCredential("US" , "Gold"),
            evidence = evidence,
            credentialSchema = CredentialSchema(
                id = "https://schema.org/PFI",
                type = "JsonSchema"
            ),
        )
```

Desired goal: 

```
        val knownCustomerCredential = VerifiableCredential.create(
            issuer = issuerBearerDid.uri.toString(),
            subject = customerBearerDid.uri.toString(),
            expirationDate = expirationDate,
            data = KccCredential("US" , "Gold"),
            evidence = evidence,
            credentialSchema = CredentialSchema(
                id = "https://schema.org/PFI",
                type = "JsonSchema"
            ),
        )
```

thanks 💖

**Comment by nitro-neal** [comment]
but the actual object that gets created Will have a type of `VerifiableCredential` right? (this is the spec)

**Comment by nitro-neal** [comment]
you should be able to add type VerifiableCredential as a workaround do 

        val knownCustomerCredential = VerifiableCredential.create(
            type = "VerifiableCredential",
            issuer = issuerBearerDid.uri.toString(),
            subject = customerBearerDid.uri.toString(),
            expirationDate = expirationDate,
            data = KccCredential("US" , "Gold"),
            evidence = evidence,
            credentialSchema = CredentialSchema(
                id = "https://schema.org/PFI",
                type = "JsonSchema"
            ),
        )

**Comment by EbonyLouis** [comment]
@nitro-neal yes @decentralgabe said it's ok for it to have the type `verifiableCredential` I don't fully understand why that's ok but the other isn't lol so it makes me think that doing this workaround won't work. 

@decentralgabe can you clarify some more please

**Comment by nitro-neal** [comment]
The VC bible says it so lol:
https://www.w3.org/TR/vc-data-model/#types

<img width="826" alt="image" src="https://github.com/TBD54566975/web5-kt/assets/5314059/0a29aaaf-a5d5-4c00-9780-a25164483e66">

**Comment by EbonyLouis** [comment]
ah ok perfect I'll use the work around- thanks @nitro-neal

**Comment by EbonyLouis** [comment]
@nitro-neal , @decentralgabe would `VerifiableCredential` being duplicated cause a problem?

**Comment by decentralgabe** [comment]
it may not create a problem it would depend on the LD processor, but we should not have duplicate values if we can avoid it

**Comment by EbonyLouis** [comment]
ok cool so yea we need the SDK updated, cause this work around will create a duplicate

**Comment by jiyoontbd** [comment]
yep, @EbonyLouis confirming you're correct - using this

```kotlin
val vc = VerifiableCredential.create(
      type = "VerifiableCredential",
      issuer = issuerDid.uri,
      subject = holderDid.uri,
      data = StreetCredibility(localRespect = "high", legit = true)
    )
```

will create a vc with the vc.vcDataModel that looks like this

![image](https://github.com/TBD54566975/web5-kt/assets/118510103/ec204d5c-832c-49a2-9f2f-f3bebd6b1d31)

pushing up a pr now :)

**Comment by EbonyLouis** [comment]
@jiyoontbd thank you! 🙌🏾
