### ISSUE TITLE
[Bug] web5-sdk-kotlin forces use of Kotlin 1.9.0

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/web5-kt#48]
**Describe the bug**
When using web5-sdk-kotlin in a project using Kotlin version 1.7.20, the build fails:
> Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1

Upgrading to Kotlin 1.9.0 resolves the issue.

**To Reproduce:**

1. Clone tbdiligence:
```
git clone git@github.com:tbdeng/tbdiligence.git
```

2. Add dependency on web5-sdk-kotlin:
```
repositories {
  maven("https://jitpack.io")
  maven("https://repo.danubetech.com/repository/maven-public/")
}
dependencies {
  implementation("com.github.TBD54566975.web5-sdk-kotlin:dids:v0.0.0-alpha")
}
```

3. Build it
```
./gradlew clean build
```

**Expected behavior:**
Successful build

**Supporting Material**
```
> Task :api:compileKotlin FAILED
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/tdaffurn/.gradle/caches/modules-2/files-2.1/com.github.TBD54566975.web5-sdk-kotlin/dids/v0.0.0-alpha/9d974df986b1cc0ea21cb93e609607e7a1853136/dids-v0.0.0-alpha.jar!/META-INF/dids.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
```

**Environment (please complete the following information):**

MacOS Sonoma
Kotlin 1.7.20
openjdk version "11.0.16.1" 2022-08-12

**Comment by nitro-neal** [comment]
@mistermoe we good on this one?
