### ISSUE TITLE
Create credentials package user guide

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/web5-kt#71]

**Comment by angiejones** [comment]
done by @EbonyLouis and @blackgirlbytes 

- https://developer.tbd.website/docs/web5/build/verifiable-credentials/vc-issuance?lang=Kotlin
- https://developer.tbd.website/docs/web5/build/verifiable-credentials/verify-vc?lang=Kotlin
- https://developer.tbd.website/docs/web5/build/verifiable-credentials/presentation-definition?lang=Kotlin
- https://developer.tbd.website/docs/web5/build/verifiable-credentials/presentation-exchange?lang=Kotlin
- https://developer.tbd.website/docs/web5/build/verifiable-credentials/jwt-to-vc?lang=Kotlin
